language: java
env:
  - MAVEN_OPTS=-Dorg.slf4j.simpleLogger.defaultLogLevel=warn
script: mvn test --batch-mode
jdk:
  - openjdk8
deploy:
  provider: releases
  api_key:
    secure: P26PBTE4oJlEhP4cPSm6NNM8cORGOJV9Qj5qYzCPvBa1ehJP8A+OUPCkliflc4YeDTLzvSqMwyQ53QJ9xRB7GfpBR2mKaej8Tn8/yKiDUFmcRtXADcXWyeD9+fQ8KP2c5ycfQzG5dtNgm+Kg3ofyFDnRBEod3LC/m7hGzDVG/u/3yRiyibjFRDHthvk0xai/rRfkb7eQajbpDnargDwyMC+kovZQ37SdkH9DHjx2dcLsARR0EG5s/b5y0vLPbNOdk8S8xkf+KsCFNuIvOdTvF0DiwzCFkdefdzFxBM2hD4q7EkHIoMXi82mImPizNLEaSBKmwOWxt9FSiLIvFzAZEsvL4C4FlYA0rQmES8tbn1LlDZNje0S9XldnH6CxtkuMLEZFZu+9IyfX0zQG0nre1vjr2mgYFv7JBoGeVjyuadwDXvlX2lyizRHXwTyUtkx6dnov7Z8mG2d84iTHD4Ee6vOS8MA9x58w03Xmt8X+yO40DvwoTsxlikyy7/FyiBlsV3/nQrJyUNq1BGcbEvw1eLGdyzn5lob3ygTql52C3fh3QGVAAebkRmfZk0UA83AYZtDzUfcOtRelx9hRxKLbDiDvj3uZRIS1JV6rzaE4DandnW5kK0MMFXpkid6lCI/OZwt7QtOQ684oRBYEBwhhx9wjmQTO5NCtQPkLwiMI1rQ=
  file: target/Midimix.bwextension
  skip_cleanup: true
  on:
    repo: klingtnet/bitwig-akai-midimix
