language: java
env:
  - MAVEN_OPTS=-Dorg.slf4j.simpleLogger.defaultLogLevel=warn
script: mvn test --batch-mode
jdk:
  - openjdk8
deploy:
  provider: releases
  api_key:
    secure: MjttP/ZbgxLQ6/e/seUjWtQCSJD71hafJ+18LtaGF663k4X1n176gASpUlTJtmlG/krjWQwmSIgGSLuyw1g4WFJXv8BQpvn1etmzg0FBtbgS7LFardL6/4e/f3QFQjMN6JJxPZ1J8QQ5g3XRGN0cAlV+s07mAug4Q3FvgZ6FUgP2Mh5iNvw44h4R0hNShFQoOp8/W/YyHmSGb6l4F20bUyhNi2JsGFIaGnX8yiuUmdAM+IhfQFF8kP1pLKRqQTWZ91cnvgVasTEHAESE2X6CRD+9PnJtyR4Tms0RRfmvnn16+Yp1PjCg2ys0U/eu90w2AB22mzPHAwGN1ljsyuHFgBF1k3ehmbX16Qj224vPBeeLD21ASAeycumui1NsE5r4vnuHQvVfuzk5UaePzTrd/UPkUL3ppmfhVlrdmZyBDsVTgCer9nvESX3sCUWqvGiuT7S7OpW0MVvk9fXtC+wI21T5WaLJQ0V8o35iZ3O4AHVQrak0PIHBRZtMhy/fng/CLP+EJYVXegVWVHQaHImgjBkd+c+dPGJGXZF8M3SyV5fadzaBlL7xNxcp3ixZbwsKfUfmeJh4sypNpi9IynfBndTh6K7rUj0/TQL9gkutuIQuYHJvb2hefNro3ePfaQYhCnDRLqcJZ6DHBQes4tqUWWBKeJn+3dBG4YcgAG4meGA=
  file: target/EdirolPCR.bwextension
  skip_cleanup: true
  on:
    repo: klingtnet/bitwig-edirol-pcr
    tags: true
