language: java
env:
- MAVEN_OPTS=-Dorg.slf4j.simpleLogger.defaultLogLevel=warn
script:
  - make test
  - make build
jdk:
- openjdk8
deploy:
  provider: releases
  api_key:
    secure: nROVxkBEAzOGOVplh9l47eqbfgCVantdIQtd/r0pHeoFuDFiFBAqnjB4LYJhncf33y0HcDMfugH37a6enfGK9Rq8hFHN5iHNAWvcDPZmu/Tb6dJ25nXaKXNJK5LCLJybje8JcNfJY1Ndr7KXgkEdBdhlLXlk8hi22Xm4Vg+ykkPJ+yVQ0QqIv78Ta1+VkFg48qZbSs0CyoqQ/2ceQFv1HsoJjDQ+CqRVuYpM+rvdSLnGbS2dfHBltaiUKza2jNsg5SNfwuhTXzIEW/h6gkJhzFFVXolaw65dFRF41FqfKgToZsYazpeTCARbUoNK8dQoCCmKD1yiXTeu7l9N21aH4LV8KF0WKTaCgUNjlpvYP6GVIEHPt2h+2ohAWbx3wgYIJOBHFjm4yguz+NHRlpN2fKsnFLQV6jaqspi5SSXjfaoQxE5ojqI4qOKayg3sn6CDJNAXGMb12ZnuRENUTJVvowN0x8c0JcIvrwNIvEvE0s0+YGAzUqSYnUnUxUUhiZhpXvvwhQXYSwOXodK1lK/YObNdAC/gAVJ0ba8uwS+pfi1fX+n3nfNzQwEcIqCpK96vQtLVCIYGweWflWHd24eiXWg7j2HusVtW///1KFGv090ynW/6cl1N7wpaOuwdbx++/yL9WUkomrOAEt0sewM1CyzDYZGFI+Pim6uHiJca1Dg=
  file: target/AkaiMPKMiniMK2.bwextension
  on:
    tags: true
    repo: klingtnet/bitwig-akai-mpk-mini-mk2
